import { describe, it, expect } from 'vitest'
import { z } from 'zod'
import { compile } from '../../../src/compiler/compile.js'
import { generateInterface } from '../../../src/compiler/generateInterface.js'
import type { MachineConfig } from '../../../src/types/machine.js'

const config: MachineConfig = {
  id: 'order',
  initial: 'pending',
  terminal: ['done'],
  context: {},
  states: {
    pending: {
      on: {
        SUBMIT: {
          target: 'done',
          guard: { name: 'hasStock', input: z.object({ sku: z.string() }) },
          actions: [
            {
              name: 'chargePayment',
              input: z.object({ amount: z.number() }),
              output: z.object({ chargeId: z.string() }),
            },
          ],
        },
      },
    },
    done: {},
  },
}

describe('generateInterface', () => {
  const compiled = compile(config, 1)
  const output = generateInterface(compiled, config)

  it('contains DO NOT EDIT banner with machine id and version', () => {
    expect(output).toContain('AUTO-GENERATED by dfsm compile')
    expect(output).toContain('Machine: order')
    expect(output).toContain('Version: 1')
  })

  it('generates action interface with correct method', () => {
    expect(output).toContain('IOrderActions')
    expect(output).toContain('chargePayment')
  })

  it('generates guard interface with correct method', () => {
    expect(output).toContain('IOrderGuards')
    expect(output).toContain('hasStock')
  })

  it('imports ActionInput from @eklabdev/dfsm', () => {
    expect(output).toContain("import type { ActionInput } from '@eklabdev/dfsm'")
  })
})
