import { zodToTs, printNode } from 'zod-to-ts'
import type { CompiledMachine } from '../types/engine.js'
import type { MachineConfig } from '../types/machine.js'

function pascalCase(str: string): string {
  return str
    .split(/[-_\s]+/)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join('')
}

export function generateInterface(
  compiled: CompiledMachine,
  config: MachineConfig,
): string {
  const name = pascalCase(compiled.machineId)
  const contextTypeName = `${name}Context`

  const actionSlots = compiled.allActionSlots
  const guardSlots = compiled.allGuardSlots

  const actionMethods = actionSlots
    .map((slot) => {
      const inputTs = printNode(zodToTs(slot.input).node)
      const outputTs = printNode(zodToTs(slot.output).node)
      return `  ${slot.name}(\n    input: ActionInput<${contextTypeName}> & ${inputTs}\n  ): Promise<${outputTs}>`
    })
    .join('\n\n')

  const guardMethods = guardSlots
    .map((slot) => {
      const inputTs = printNode(zodToTs(slot.input).node)
      return `  ${slot.name}(\n    input: ActionInput<${contextTypeName}> & ${inputTs}\n  ): boolean | Promise<boolean>`
    })
    .join('\n\n')

  return `// AUTO-GENERATED by dfsm compile — DO NOT EDIT
// Machine: ${compiled.machineId}  Version: ${compiled.version}
// Re-run 'dfsm compile' after editing the machine config.

import type { ActionInput } from '@eklabdev/dfsm'

export interface I${name}Actions {
${actionMethods}
}

export interface I${name}Guards {
${guardMethods}
}
`
}
